### ISSUE TITLE
issue with geometries?

### ISSUE THREAD

**Issue by riccardoklinger** [michaelmgis/osmdata.xyz#15] opened 2020-02-20 00:33 UTC
I've downloaded boundaries and sleetced boundary=administrative and admin_level=2. India is part of the list, but when zoomed to india, the dataset is simply way to small in its geometry. 
I've pushed the data to postgis using

ogr2ogr -f PostgreSQL "PG:user=XXX host=localhost password=XXX dbname=XXX " "/Volumes/My Passport/boundary_EPSG4326.gpkg"

but India looks like this:
<img width="1211" alt="grafik" src="https://user-images.githubusercontent.com/7377897/74889330-eddfae00-5380-11ea-9031-dcd633118bb8.png">
any idea what was going wrong?!

**Comment by riccardoklinger** [comment] 2020-02-20 01:29
also quicksearch was not showing up India with the following query:
<osm-script output="xml" timeout="125">
    <union>
        <query type="node">
            <has-kv k="boundary" v="administrative"/>
 <has-kv k="admin_level" v="2"/>
        </query>
        <query type="way">
            <has-kv k="boundary" v="administrative"/>
 <has-kv k="admin_level" v="2"/>
        </query>
        <query type="relation">
            <has-kv k="boundary" v="administrative"/>
 <has-kv k="admin_level" v="2"/>

        </query>
    </union>
    <union>
        <item/>
        <recurse type="down"/>
    </union>
    <print mode="body"/>
</osm-script>

**Comment by riccardoklinger** [comment] 2020-02-20 01:29
seem like a fcuked up geometry. also for other countries . not onyl in osmdata.xyz but also quickmap. 

>

**Comment by riccardoklinger** [comment] 2020-02-20 01:32
ah, when we are importing the dump files into the pg for the first ti,me, we assume it is of type Polygon. Yet it is Multipolygon. We should switch this to 
-nlt PROMOTE_TO_MULTI instead. Maybe this would help?!
```
-nlt POLYGON -update PG:"host=$host port=$port dbname=osmdata user=osmdata password=osmdata" \
		-sql "select * from import.osm_polygon where '$i' <> ''"
```

**Comment by riccardoklinger** [comment] 2020-02-20 16:07
here is one major problem in the geometry in OSM: 
<img width="1988" alt="grafik" src="https://user-images.githubusercontent.com/7377897/74954423-638c5e00-5403-11ea-9dfd-0f4246c6678b.png">

**Comment by michaelmgis** [comment] 2020-02-21 09:05
Regarding the [documentation ](https://imposm.org/docs/imposm3/latest/relations.html#multipolygons)of imposm:

> Multipolygon relations are automatically handled by Imposm for all polygon tables.

**Comment by michaelmgis** [comment] 2020-03-27 16:10
Can we close this issue since it is related to the osm database itself?

**Comment by michaelmgis** [comment] 2020-10-06 16:57
Since the issue is not active, I close it.

**Closed** 2020-10-06 16:57 UTC
